In [2]:
print("Hello")

Hello

In [36]:
# 텍스트 파일 읽기
f=open("./text/name1.txt", "r", encoding="utf-8")
data = f.read()
print(data)

In [35]:
# 입력받아 쓰기
f=open("./text/name1.txt", "w", encoding="utf-8")
while True:
    team = input("팀:")
    if not team:
        break
    f.write(team+"\n")
f.close()

KeyboardInterrupt: Interrupted by user

In [4]:
# 입력받아 쓰기
f=open("./text/name2.txt", "w", encoding="utf-8")
while True:
    team = input("팀:")
    if not team:
        break
    f.write(team+"\n")
f.close()

In [4]:
## 엑셀 파일 pandas 라이브러리로 불러오기
import pandas as pd
df = pd.read_excel('./assets/my_grade.xlsx')
# 데이터프레임의 전체 행에서 상위/하위 5개(기본값)의 행만 가져온다.
df.head()
df.tail()

   이름  1차 지필  2차 지필  수행1  수행2 등급
0  유비     92     88   93   95  A
1  관우     89     90   85   78  B
2  장비     71     84   67   70  C

In [ ]:
## 학교 동아리 연습문제 : club.xlsx

In [54]:
import pandas as pd
df = pd.read_excel('./assets/club.xlsx')
df.head()
add_df = pd.DataFrame([{
    '학번': 10512,
    '이름': '김하늘',
    '학년': 1,
    '동아리': 'AI 연구부',
    '역할': '부원'
}])

new_df= pd.concat([df, add_df])
new_df.to_excel('./assets/new_club.xlsx', index=False)
data = pd.read_excel('./assets/new_club.xlsx')
data

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원
3  10512  김하늘   1  AI 연구부  부원